name: Repo File Sync - Client

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Destination Repository
        uses: actions/checkout@v3

      - name: Sync Files from Client Repository
        uses: repo-sync/github-sync@v3.3.0
        with:
          source_repo: Tuananh4403/PetHealthClient
          source_branch: main
          destination_repo: ${{ github.repository }}
          destination_branch: main
          delete_orphaned_files: true
          force_update: true
          token: ${{ secrets.SOURCE_REPO_TOKEN }}
          # Customize files to include or exclude for client
          include: |
            client/*
          exclude: |
            sys/*

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Sync client files from source repository'
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
